services:
  - type: web
    name: hydra-compliance-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: hydra-compliance-index
      - key: PINECONE_CLOUD
        value: aws
      - key: PINECONE_REGION
        value: us-east-1
      - key: EMBEDDING_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
      - key: EMBEDDING_DIMENSION
        value: "384"
      - key: LLM_PROVIDER
        value: ollama
      - key: OLLAMA_MODEL
        value: llama3.2:3b